export class ApplicationForm {
    applicationId: number = 0;
    firstName: any;
    lastName: any;
    email: any;
    phoneNo: any;
    dateOfBirth: any;
    nationality: any;
    countryOfResident: any;
    adress: any;
    parentFirstName: any;
    parentLastName: any;
    parentPhoneNo: any;
    parentEmail: any;
    dateOfStudy: any;
    intake: number = 0;
    courseName: number = 0;
    studyLocation: number = 0;
    suggestedUniversity: any;
    lastSchoolQualification: any;
    secondarySchoolName: any;
    schoolCompletionYear: any;
    feePayby: number = 0;
    feePaybyDetail: any;
    socialRefrenceType: number = 0;
    socialRefrenceTypeDetails: any;
    hasExistMedicalCondition?: boolean;
    medicalConditionDetail: any;
    hasVisa?: boolean;
    visaType: number = 0;
    visaTypeDetail: any;
    applicationStatus: number = 0;
    applicationSource: number = 0;
    socialReferance: any;
    feePayByData: any;
    course: any;
    campusData: any;
    stageIds: any;
    applicationStatusName: any;
}
